In [8]:
def isprime(p):
    count=0
    for i in range(1,p+1):
            if  (p%i==0):
                count=count+1
    if count==2:
        return True
    else:
        return False
                                                           
               

In [9]:
lb=2
ub=100
def prim_range(lb,ub):
    for i in range(lb,ub+1):
        if isprime(i):
            print(i,end=' ')
prim_range(lb,ub)            

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

## MAPS:
syntax:map(function,iterable)

In [26]:
l =list(map(int,['1','2','3']))
print(l)


[1, 2, 3]


In [27]:
l =tuple(map(int,['1','2','3']))
print(l)

(1, 2, 3)


In [20]:
list(map(str,l))


['1', '2', '3']

In [21]:
i = input().split()

python program


In [24]:
list(map(str,input()))

program


['p', 'r', 'o', 'g', 'r', 'a', 'm']

In [34]:
def addition(n):
    return n+n

In [35]:
list(map(addition,[4,7,8,9,2,10]))

[8, 14, 16, 18, 4, 20]

In [41]:
list(map(float,[4,6,7,8]))

[4.0, 6.0, 7.0, 8.0]

In [38]:
def power(n):
    return n**n

In [39]:
list(map(power,[4,5,7,8]))

[256, 3125, 823543, 16777216]

In [10]:
def sqrt(n):
    return n*n
l=list(map(sqrt,[1,2,3,4,5,6]))
print(l)

[1, 4, 9, 16, 25, 36]


## FILTERS

## [1 2 3 4 5 6 7 8 9]
.prime
.even
.odd

In [53]:
Li = [1,2,'a','b','c',3]
def isdigit(n):
    n = str(n)
    if n.isdigit():
        return True
    return False
list(filter(isdigit,Li))
        

[1, 2, 3]

In [5]:
Li = [1,2,6,8,4,3,9]
def even(n):
    if(n%2==0):
        return True
    return False 
def odd(n):
    if(n%2!= 0):
        
        return True
    return False
def prime(n):
    if(n<2):
        
        return False
    for i in range(2,n//2+1):
        if(n%i == 0):
            
            return False

    return True
print(list(filter(even,Li)))
print(list(filter(odd,Li)))
print(list(filter(prime,Li)))
   
       

        

            
   

        

[2, 6, 8, 4]
[1, 3, 9]
[2, 3]


## LAMBDA
syntax: lambda argument:expression

In [12]:
h = lambda x: x%2==0
list(filter(h,[1,2,3,4,5]))

[2, 4]

In [13]:
l=[1,2,3,4,5,6,7,8,9]
o=lambda i:i%2!=0
list(filter(o,l))

[1, 3, 5, 7, 9]

In [17]:
from random import randint as r
for i in range(1,10+1):
    
     print(r(1,25))

25
6
18
20
23
1
10
17
10
9


In [19]:
m1 = [r(1,25) for i in range(1,11)]
m2 = [r(1,25) for i in range(1,11)]
m3 = [r(1,25) for i in range(1,11)]
print(m1)
print(m2)
print(m3)


[7, 8, 20, 8, 10, 23, 15, 1, 4, 4]
[24, 20, 23, 13, 15, 3, 9, 20, 6, 11]
[18, 3, 4, 24, 14, 7, 23, 7, 11, 12]


In [22]:
a1 = list(map(lambda x,y:(x+y)//2,m1,m2))
print(a1)

[15, 14, 21, 10, 12, 13, 12, 10, 5, 7]


In [28]:
a2 = list(map(lambda x,y,z:(x+y+z)//3,m1,m2,m3))
print(a2)


[16, 10, 15, 15, 13, 11, 15, 9, 7, 9]


In [ ]:
list(map(f,ite))
list(map(f,list))

In [29]:
list(filter(lambda x:x<10,a1))

[5, 7]

In [30]:
list(filter(lambda x:x<10,a2))

[9, 7, 9]

In [33]:
list(filter(lambda x:x>10,a1))

[15, 14, 21, 12, 13, 12]

In [32]:
list(filter(lambda x:x>10,a2))

[16, 15, 15, 13, 11, 15]

## NUMPY

In [34]:
import numpy as np


In [36]:
l = [1,2,3,4,5,6]
a1 = np.array(l)
print(a1)

[1 2 3 4 5 6]


In [37]:
l1 = [[1,2,3],[4,5,6]]
a2 = np.array(l1)
print(a2)

[[1 2 3]
 [4 5 6]]


In [38]:
l3 = [[1,2,3],[4,5,6],[7,8,9]]
a3 = np.array(l3)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
a= np.arange(100).reshape(10,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [52]:
b = np.arange(8).reshape(2,4)
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [57]:
s = np.arange(6).reshape(2,3)
print(s)

[[0 1 2]
 [3 4 5]]


In [58]:
a= np.arange(6).reshape(2,3)
b= np.arange(6).reshape(2,3)
c= np.arange(6).reshape(2,3)
print(a)
print(b)
print(c)


[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


In [59]:
a+b

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [60]:
b-c

array([[0, 0, 0],
       [0, 0, 0]])

In [61]:
print(np.cos(a))

[[ 1.          0.54030231 -0.41614684]
 [-0.9899925  -0.65364362  0.28366219]]


In [62]:
print(np.shape(c))

(2, 3)


In [63]:
print(np.sin(b))

[[ 0.          0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]]
